/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pushdown_automata;

import pushdown_automata.more1than0.Q0;
import pushdown_automata.more1than0.Q1;
import pushdown_automata.more1than0.Q2;

import java.util.Stack;

public class App {
    public static void main(String[] args) {
        if (run("101011001")){
            System.out.println("Accepted");
        } else {
            System.out.println("Rejected");
        }
    }

    public static boolean run(String word){
        Stack<String> stack = new Stack<>();
        Q0 q0 = new Q0("Q0", stack);
        Q1 q1 = new Q1("Q1", stack);
        Q2 q2 = new Q2("Q2", stack);
        q0.setStates(q1, q2);
        q1.setStates(q0, q2);
        q2.setStates(q1);

        return q0.changeToState(word);
    }
}
